User/asroman/metu sparg dataset integration
iranroman/SpatialScaper pull request #2
Opened 2023-05-14 06:30 UTC by adrianSRoman

Take em32 RIRs data and integrate it into DCASE synth format:

METU Sparg data parameters:
```
Number of trajectories = 1
Number of heights = 7
Number of samples per IR (Nsamp)= 48000
Number of channels per IR (Nch)= 32 (em32), 4 (MIC)
```

Data structure brief:
```
doa_xyz = list_of_trayectories_([list_of_heights_([x, y, z])])
rir = list_of_trayectories_([list_of_heights_(np.array(Nch, Nsamp)])
```

Assumtions:
- Circular trajectory TAU RIR is equivalent to a square trajectory in METU Sparg
- MIC raw channels correspond to channels 6,10,26,22 from the Sparg eigenmike data

2023-05-14 18:59 UTC, iranroman commented on metusparg/sparg_meas_to_pickle.py
> +        y = (3 - int(num[2])) * 0.3
I thought the METU documentation said that `y = (3-Y)*0.5`

<img width="107" alt="Screen Shot 2023-05-14 at 2 59 34 PM" src="https://github.com/iranroman/SELD-data-generator/assets/18207454/6b022dcc-ba52-42f4-9e21-e91d0475d35a">

2023-05-16 16:29 UTC, ChrisIck requested changes
All of this looks good to me. Thanks for putting all of the metusparg-specific files in their own directory, we will probably need some tools like this for each dataset, so each will have their own directory.

My only suggestion is to revert changes to the `generation_parameters.py` file since that should be evergreened for posterity's sake, or setup for a general baseline, but what you're doing makes sense for now at least.

2023-05-16 16:29 UTC, ChrisIck commented on generation_parameters.py
In general, since we are all using different versions of `generation_parameters.py`, we should avoid pushing our individual edits to main. Adding `metu` to the `rooms2fold` is a good stopgap, but hopefully this can all be addressed as we work on #6 .

2023-05-17 06:27 UTC, adrianSRoman commented on generation_parameters.py
Looks like Iran merge onto my branch and so your comments made it here.

In this PR I have removed a bunch of the hard-coded junk under `generation_parameters.py` and adopted instead the `.yaml` approach. For the formal PR I will make sure I add a generic yaml file. In the meantime for development we can define our own yamls

2023-05-22 17:47 UTC, ChrisIck commented on generation_parameters.py
We should do the `.yaml` swap in a separate branch/PR; the purpose of this PR is the metu integration, no? Shouldn't have multiple issues in the same branch, maybe separate this out for later `.yaml` integration.

@iranroman can you chime in on this?

2023-05-22 17:48 UTC, ChrisIck commented on yaml/gen_params.yaml
Same comment as on `generation_parameters.py`, we should save this translation for a separate PR as it's a different issue than is being addressed in this PR.

2023-05-22 17:49 UTC, ChrisIck commented on audio_synthesizer.py
> +                        eventsig, fs_db = soundfile.read(self._db_path + '/' + filename)
Should use `os.path.join` for safe filename building

2023-05-23 06:26 UTC, adrianSRoman commented on generation_parameters.py
Good point, I got a bit desperate on the hard-coded dictionary from before and brought this in for my development. I will revert this `.yaml` change on this PR.

2023-05-23 06:26 UTC, adrianSRoman commented on yaml/gen_params.yaml
Agreed!

2024-04-10 02:48 UTC, iranroman commented
METU has been integrated in #39

2024-04-10 02:48 UTC, closed without merging